/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.remocamp.view;

import br.com.remocamp.controller.RemocaoController;
import br.com.remocamp.model.Remocao;
import javax.swing.JOptionPane;

/**
 *
 * @author fabiano
 */
public class FormularioRemocao extends javax.swing.JInternalFrame {

    /**
     * Creates new form NovoJInternalFrame
     */
    private int idRemocao; 
    private java.sql.Date inicio;//solicitacao
    private java.sql.Date fim;//remocao
    private String ambulancia;
    private com.toedter.calendar.JDateChooser dateInicio;
    private com.toedter.calendar.JDateChooser dateFim;
    
    public FormularioRemocao() {
        initComponents();
        btnEditar.setVisible(false);
        btnImpressao.setVisible(false);
        btnHistorico.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPaciente = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        lbIdade = new javax.swing.JLabel();
        panelDiagnostico = new javax.swing.JPanel();
        jScrollPaneDiagnostico = new javax.swing.JScrollPane();
        txtAreaDiagnostico = new javax.swing.JTextArea();
        lbVaga = new javax.swing.JLabel();
        checkBoxVaga = new javax.swing.JCheckBox();
        panelDataSolicitacao = new javax.swing.JPanel();
        dateChooserSolicitacao = new com.toedter.calendar.JDateChooser();
        panelDataRemocao = new javax.swing.JPanel();
        dateChooserRemocao = new com.toedter.calendar.JDateChooser();
        panelEquipe = new javax.swing.JPanel();
        lbMedico = new javax.swing.JLabel();
        lbEnfermeiro = new javax.swing.JLabel();
        lbMotorista = new javax.swing.JLabel();
        lbOperador = new javax.swing.JLabel();
        txtMedico = new javax.swing.JTextField();
        txtEnfermeiro = new javax.swing.JTextField();
        txtMotorista = new javax.swing.JTextField();
        txtOperador = new javax.swing.JTextField();
        panelAmbulancia = new javax.swing.JPanel();
        checkBoxUTI = new javax.swing.JCheckBox();
        checkBoxBasica = new javax.swing.JCheckBox();
        checkBoxSimples = new javax.swing.JCheckBox();
        panelObs = new javax.swing.JPanel();
        jScrollPaneObs = new javax.swing.JScrollPane();
        txtAreaObs = new javax.swing.JTextArea();
        lbResponsavel = new javax.swing.JLabel();
        txtResponsavel = new javax.swing.JTextField();
        lbUnidMedico = new javax.swing.JLabel();
        txtUnidMedico = new javax.swing.JTextField();
        panelDestino = new javax.swing.JPanel();
        lbComplementoDestino = new javax.swing.JLabel();
        lbEnderecoDestino = new javax.swing.JLabel();
        lbEstadoDestino = new javax.swing.JLabel();
        txtCidadeDestino = new javax.swing.JTextField();
        txtEnderecoDestino = new javax.swing.JTextField();
        lbCidadeDestino = new javax.swing.JLabel();
        txtComplementoDestino = new javax.swing.JTextField();
        txtEstadoDestino = new javax.swing.JTextField();
        panelOrigem = new javax.swing.JPanel();
        txtComplementoOrigem = new javax.swing.JTextField();
        lbHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        lbComplementoOrigem = new javax.swing.JLabel();
        lbEnderecoOrigem = new javax.swing.JLabel();
        lbCidadeOrigem = new javax.swing.JLabel();
        txtCidadeOrigem = new javax.swing.JTextField();
        txtEnderecoOrigem = new javax.swing.JTextField();
        lbEstadoOrigem = new javax.swing.JLabel();
        txtEstadoOrigem = new javax.swing.JTextField();
        btnGravar = new javax.swing.JButton();
        btnImpressao = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnHistorico = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Formulário Remoção");

        panelPaciente.setBorder(javax.swing.BorderFactory.createTitledBorder("Paciente"));

        lbNome.setText("*Nome :");

        lbIdade.setText("*Idade :");

        panelDiagnostico.setBorder(javax.swing.BorderFactory.createTitledBorder("*Diagnóstico"));

        txtAreaDiagnostico.setColumns(20);
        txtAreaDiagnostico.setRows(5);
        jScrollPaneDiagnostico.setViewportView(txtAreaDiagnostico);

        javax.swing.GroupLayout panelDiagnosticoLayout = new javax.swing.GroupLayout(panelDiagnostico);
        panelDiagnostico.setLayout(panelDiagnosticoLayout);
        panelDiagnosticoLayout.setHorizontalGroup(
            panelDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiagnosticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneDiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDiagnosticoLayout.setVerticalGroup(
            panelDiagnosticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiagnosticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbVaga.setText("Vaga Confirmada");

        panelDataSolicitacao.setBorder(javax.swing.BorderFactory.createTitledBorder("*Data de solicitação"));

        javax.swing.GroupLayout panelDataSolicitacaoLayout = new javax.swing.GroupLayout(panelDataSolicitacao);
        panelDataSolicitacao.setLayout(panelDataSolicitacaoLayout);
        panelDataSolicitacaoLayout.setHorizontalGroup(
            panelDataSolicitacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataSolicitacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateChooserSolicitacao, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDataSolicitacaoLayout.setVerticalGroup(
            panelDataSolicitacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataSolicitacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateChooserSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelDataRemocao.setBorder(javax.swing.BorderFactory.createTitledBorder("*Data de remoção"));

        javax.swing.GroupLayout panelDataRemocaoLayout = new javax.swing.GroupLayout(panelDataRemocao);
        panelDataRemocao.setLayout(panelDataRemocaoLayout);
        panelDataRemocaoLayout.setHorizontalGroup(
            panelDataRemocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataRemocaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateChooserRemocao, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDataRemocaoLayout.setVerticalGroup(
            panelDataRemocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataRemocaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateChooserRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelPacienteLayout = new javax.swing.GroupLayout(panelPaciente);
        panelPaciente.setLayout(panelPacienteLayout);
        panelPacienteLayout.setHorizontalGroup(
            panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDiagnostico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbVaga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxVaga)
                .addGap(28, 28, 28)
                .addComponent(panelDataSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(panelDataRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelPacienteLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbNome)
                .addGap(22, 22, 22)
                .addComponent(txtNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        panelPacienteLayout.setVerticalGroup(
            panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIdade)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbVaga)
                    .addComponent(checkBoxVaga)
                    .addComponent(panelDataSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDataRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelPacienteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbIdade, lbNome, txtIdade, txtNome});

        panelEquipe.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipe"));

        lbMedico.setText("*Médico :");

        lbEnfermeiro.setText("*Enfermeiro(a) :");

        lbMotorista.setText("*Condutor:");

        lbOperador.setText("*Operador(a) :");

        txtMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicoActionPerformed(evt);
            }
        });

        txtEnfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnfermeiroActionPerformed(evt);
            }
        });

        txtMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotoristaActionPerformed(evt);
            }
        });

        txtOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOperadorActionPerformed(evt);
            }
        });

        panelAmbulancia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "*Ambulancia"));

        checkBoxUTI.setText("UTI");
        checkBoxUTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxUTIActionPerformed(evt);
            }
        });

        checkBoxBasica.setText("Básica");
        checkBoxBasica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxBasicaActionPerformed(evt);
            }
        });

        checkBoxSimples.setText("Simples");
        checkBoxSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSimplesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAmbulanciaLayout = new javax.swing.GroupLayout(panelAmbulancia);
        panelAmbulancia.setLayout(panelAmbulanciaLayout);
        panelAmbulanciaLayout.setHorizontalGroup(
            panelAmbulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAmbulanciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAmbulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxUTI)
                    .addComponent(checkBoxBasica)
                    .addComponent(checkBoxSimples))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelAmbulanciaLayout.setVerticalGroup(
            panelAmbulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAmbulanciaLayout.createSequentialGroup()
                .addComponent(checkBoxUTI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxBasica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxSimples)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelEquipeLayout = new javax.swing.GroupLayout(panelEquipe);
        panelEquipe.setLayout(panelEquipeLayout);
        panelEquipeLayout.setHorizontalGroup(
            panelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbOperador)
                    .addComponent(lbMotorista)
                    .addComponent(lbEnfermeiro)
                    .addComponent(lbMedico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelAmbulancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        panelEquipeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEnfermeiro, txtMedico, txtMotorista, txtOperador});

        panelEquipeLayout.setVerticalGroup(
            panelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEquipeLayout.createSequentialGroup()
                        .addGroup(panelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEquipeLayout.createSequentialGroup()
                                .addComponent(lbMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbEnfermeiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbMotorista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbOperador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelEquipeLayout.createSequentialGroup()
                                .addComponent(txtMedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEnfermeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMotorista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOperador)))
                        .addGap(18, 18, 18))
                    .addGroup(panelEquipeLayout.createSequentialGroup()
                        .addComponent(panelAmbulancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        panelObs.setBorder(javax.swing.BorderFactory.createTitledBorder("Obs"));

        txtAreaObs.setColumns(20);
        txtAreaObs.setRows(5);
        jScrollPaneObs.setViewportView(txtAreaObs);

        lbResponsavel.setText("*Responsável :");

        lbUnidMedico.setText("*Unid/Médico :");

        javax.swing.GroupLayout panelObsLayout = new javax.swing.GroupLayout(panelObs);
        panelObs.setLayout(panelObsLayout);
        panelObsLayout.setHorizontalGroup(
            panelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneObs)
                    .addGroup(panelObsLayout.createSequentialGroup()
                        .addComponent(lbResponsavel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbUnidMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUnidMedico)))
                .addContainerGap())
        );
        panelObsLayout.setVerticalGroup(
            panelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObsLayout.createSequentialGroup()
                .addComponent(jScrollPaneObs, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbResponsavel)
                    .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUnidMedico)
                    .addComponent(txtUnidMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelDestino.setBorder(javax.swing.BorderFactory.createTitledBorder("Destino"));

        lbComplementoDestino.setText("Complemento :");

        lbEnderecoDestino.setText("*Endereço :");

        lbEstadoDestino.setText("*Estado :");

        lbCidadeDestino.setText("*Cidade :");

        txtEstadoDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoDestinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDestinoLayout = new javax.swing.GroupLayout(panelDestino);
        panelDestino.setLayout(panelDestinoLayout);
        panelDestinoLayout.setHorizontalGroup(
            panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEnderecoDestino)
                    .addComponent(lbCidadeDestino)
                    .addComponent(lbComplementoDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEnderecoDestino)
                    .addGroup(panelDestinoLayout.createSequentialGroup()
                        .addGroup(panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtComplementoDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(txtCidadeDestino, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(32, 32, 32)
                        .addComponent(lbEstadoDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstadoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDestinoLayout.setVerticalGroup(
            panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnderecoDestino)
                    .addComponent(txtEnderecoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidadeDestino)
                    .addComponent(txtCidadeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstadoDestino)
                    .addComponent(txtEstadoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComplementoDestino)
                    .addComponent(txtComplementoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelOrigem.setBorder(javax.swing.BorderFactory.createTitledBorder("Origem"));

        txtComplementoOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoOrigemActionPerformed(evt);
            }
        });

        lbHora.setText("*Hora :");

        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });

        lbComplementoOrigem.setText("Complemento :");

        lbEnderecoOrigem.setText("*Endereço :");

        lbCidadeOrigem.setText("*Cidade :");

        lbEstadoOrigem.setText("*Estado : ");

        txtEstadoOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoOrigemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOrigemLayout = new javax.swing.GroupLayout(panelOrigem);
        panelOrigem.setLayout(panelOrigemLayout);
        panelOrigemLayout.setHorizontalGroup(
            panelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrigemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOrigemLayout.createSequentialGroup()
                        .addGroup(panelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCidadeOrigem)
                            .addComponent(lbEnderecoOrigem)
                            .addComponent(lbComplementoOrigem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOrigemLayout.createSequentialGroup()
                                .addGroup(panelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtComplementoOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(txtCidadeOrigem))
                                .addGap(32, 32, 32)
                                .addComponent(lbEstadoOrigem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstadoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtEnderecoOrigem)))
                    .addGroup(panelOrigemLayout.createSequentialGroup()
                        .addComponent(lbHora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelOrigemLayout.setVerticalGroup(
            panelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrigemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnderecoOrigem)
                    .addComponent(txtEnderecoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidadeOrigem)
                    .addComponent(txtCidadeOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstadoOrigem)
                    .addComponent(txtEstadoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComplementoOrigem)
                    .addComponent(txtComplementoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHora)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnImpressao.setText("Vizualizar impressão");
        btnImpressao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpressaoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnHistorico.setText("Histórico de Tratativas");
        btnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelPaciente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelOrigem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelEquipe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelObs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImpressao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGravar)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImpressao)
                    .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar)
                    .addComponent(btnHistorico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnGravar, btnImpressao});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtComplementoOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoOrigemActionPerformed

    private void txtMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicoActionPerformed

    private void txtMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotoristaActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_txtMotoristaActionPerformed

    private void txtEnfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnfermeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnfermeiroActionPerformed

    private void txtOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOperadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOperadorActionPerformed

    private void checkBoxUTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxUTIActionPerformed
        if (checkBoxBasica.isSelected() || checkBoxSimples.isSelected()) {
            checkBoxBasica.setSelected(false);
            checkBoxSimples.setSelected(false);
        }
    }//GEN-LAST:event_checkBoxUTIActionPerformed

    private void checkBoxBasicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxBasicaActionPerformed
       if (checkBoxSimples.isSelected() || checkBoxUTI.isSelected()) {
            checkBoxSimples.setSelected(false);
            checkBoxUTI.setSelected(false);
        }
    }//GEN-LAST:event_checkBoxBasicaActionPerformed

    private void txtEstadoDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoDestinoActionPerformed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void checkBoxSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSimplesActionPerformed
        if (checkBoxBasica.isSelected() || checkBoxUTI.isSelected()) {
            checkBoxBasica.setSelected(false);
            checkBoxUTI.setSelected(false);
        }
    }//GEN-LAST:event_checkBoxSimplesActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        if (validarFormulario()) {
            RemocaoController controller = new RemocaoController(this);
            controller.gravarFormulario();
            btnImpressao.setVisible(true);
            btnGravar.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Os campos obrigatórios não foram preenchidos", "Validação de formulário", JOptionPane.ERROR_MESSAGE);
        }    
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        statusAllTxtField(true);

        if (btnEditar.getText().equals("Gravar")) {
            if (validarFormulario()) {
                RemocaoController controller = new RemocaoController(this);
                FormularioRemocao remocaoFormulario = controller.updateRemocao();
                dispose();
                Principal.desktopPane.add(remocaoFormulario);
                remocaoFormulario.setVisible(true);
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Os campos obrigatórios não foram preenchidos", "Validação de formulário", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        if (btnEditar.getText().equals("Editar")) {
            btnEditar.setText("Gravar");
            btnVisualizarImpressaoVisible(false);
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnImpressaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpressaoActionPerformed
        RemocaoController clt = new RemocaoController(this);
        clt.gerarFormulario();
    }//GEN-LAST:event_btnImpressaoActionPerformed

    private void txtEstadoOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoOrigemActionPerformed

    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        HistoricodeTratativas historico = new HistoricodeTratativas(this,idRemocao);
        Principal.desktopPane.add(historico).setLocation(85, 0);
        historico.setVisible(true);
    }//GEN-LAST:event_btnHistoricoActionPerformed
    
    private boolean validarFormulario(){
        if(txtNome.getText().isEmpty()){
            return false;
        }else if(txtIdade.getText().isEmpty()){
            return false;
        }else if(dateChooserSolicitacao == null){
            return false;
        }else if(dateChooserRemocao == null){
            return false;
        }else if(txtAreaDiagnostico.getText().isEmpty()){
            return false;
        }else if(txtEnderecoOrigem.getText().isEmpty()){
            return false;
        }else if(txtCidadeOrigem.getText().isEmpty()){
            return false;
        }else if(txtEstadoOrigem.getText().isEmpty()){
            return false;
        }else if(txtHora.getText().isEmpty()){
            return false;
        }else if(txtEnderecoDestino.getText().isEmpty()){
            return false;
        }else if(txtCidadeDestino.getText().isEmpty()){
            return false;
        }else if(txtEstadoDestino.getText().isEmpty()){
            return false;
        }else if(txtMedico.getText().isEmpty()){
            return false;
        }else if(txtEnfermeiro.getText().isEmpty()){
            return false;
        }else if(txtMotorista.getText().isEmpty()){
            return false;
        }else if(txtOperador.getText().isEmpty()){
            return false;
        }else if(txtResponsavel.getText().isEmpty()){
            return false;
        }else if(txtUnidMedico.getText().isEmpty()){
            return false;
        }else return !getAmbulancia().equals("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton btnImpressao;
    private javax.swing.JCheckBox checkBoxBasica;
    private javax.swing.JCheckBox checkBoxSimples;
    private javax.swing.JCheckBox checkBoxUTI;
    private javax.swing.JCheckBox checkBoxVaga;
    private com.toedter.calendar.JDateChooser dateChooserRemocao;
    private com.toedter.calendar.JDateChooser dateChooserSolicitacao;
    private javax.swing.JScrollPane jScrollPaneDiagnostico;
    private javax.swing.JScrollPane jScrollPaneObs;
    private javax.swing.JLabel lbCidadeDestino;
    private javax.swing.JLabel lbCidadeOrigem;
    private javax.swing.JLabel lbComplementoDestino;
    private javax.swing.JLabel lbComplementoOrigem;
    private javax.swing.JLabel lbEnderecoDestino;
    private javax.swing.JLabel lbEnderecoOrigem;
    private javax.swing.JLabel lbEnfermeiro;
    private javax.swing.JLabel lbEstadoDestino;
    private javax.swing.JLabel lbEstadoOrigem;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbIdade;
    private javax.swing.JLabel lbMedico;
    private javax.swing.JLabel lbMotorista;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbOperador;
    private javax.swing.JLabel lbResponsavel;
    private javax.swing.JLabel lbUnidMedico;
    private javax.swing.JLabel lbVaga;
    private javax.swing.JPanel panelAmbulancia;
    private javax.swing.JPanel panelDataRemocao;
    private javax.swing.JPanel panelDataSolicitacao;
    private javax.swing.JPanel panelDestino;
    private javax.swing.JPanel panelDiagnostico;
    private javax.swing.JPanel panelEquipe;
    private javax.swing.JPanel panelObs;
    private javax.swing.JPanel panelOrigem;
    private javax.swing.JPanel panelPaciente;
    private javax.swing.JTextArea txtAreaDiagnostico;
    private javax.swing.JTextArea txtAreaObs;
    private javax.swing.JTextField txtCidadeDestino;
    private javax.swing.JTextField txtCidadeOrigem;
    private javax.swing.JTextField txtComplementoDestino;
    private javax.swing.JTextField txtComplementoOrigem;
    private javax.swing.JTextField txtEnderecoDestino;
    private javax.swing.JTextField txtEnderecoOrigem;
    private javax.swing.JTextField txtEnfermeiro;
    private javax.swing.JTextField txtEstadoDestino;
    private javax.swing.JTextField txtEstadoOrigem;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtMotorista;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtOperador;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextField txtUnidMedico;
    // End of variables declaration//GEN-END:variables

    private void setAmbulanciaFormulario(Remocao remocao) {

        String tipo = remocao.getAmbulancia();

        if (tipo.equals("UTI")) {
            checkBoxUTI.setSelected(true);
        } else if (tipo.equals("Basica")) {
            checkBoxBasica.setSelected(true);
        } else {
            checkBoxSimples.setSelected(true);
        }
    }
    
    public int getIdRemocao() {
        return idRemocao;
    }

    public void setIdRemocao(int idRemocao) {
        this.idRemocao = idRemocao;
    }
    
    public String getNome(){
        return txtNome.getText();
    }
    
    public void setNome(String nome){
        this.txtNome.setText(nome);
    }
    
    public String getIdade(){
        return txtIdade.getText();
    }
    
    public void setIdade(String idade){
        this.txtIdade.setText(idade);
    }
    
    public String getvagaConfirmada(){
        if(checkBoxVaga.isSelected()){
            return "Sim";
        }
       return "Não";
    }
    
    public void setVagaConfirmada(String vaga) {
        if (vaga.equals("Sim")) {
            checkBoxVaga.setSelected(true);
        } else {
            checkBoxVaga.setSelected(false);
        }
    }
    
    public com.toedter.calendar.JDateChooser getDataChooserSolicitacao(){
        setDataChooserSolicitacao(dateChooserSolicitacao);
        return dateInicio;
        
    }
    
    public void setDataChooserSolicitacao(com.toedter.calendar.JDateChooser dataSolicitacao){
        dateInicio = dataSolicitacao;
    }
    
    public com.toedter.calendar.JDateChooser getDataChoserRemocao(){
        setDataChooserRemocao(dateChooserRemocao);
        return dateFim;
    }
    
    public void setDataChooserRemocao(com.toedter.calendar.JDateChooser dataRemocao){
        dateFim = dataRemocao;
    }
    
    public java.sql.Date getSolicitacao() {
        return inicio;
    }

    public void setSolicitacao(java.sql.Date solicitacao) {
        this.inicio = solicitacao;
    }
    
    public java.sql.Date getRemocao() {
        return fim;
    }

    public void setRemocao(java.sql.Date remocao) {
        this.fim = remocao;
    }
    
    public String getDiagnostico(){
        return txtAreaDiagnostico.getText();
    }
    
    public void setDiagnostico(String diagnostico){
        this.txtAreaDiagnostico.setText(diagnostico);
    }
    
    public String getEnderecoOrigem(){
        return txtEnderecoOrigem.getText();
    }
    
    public void setEnderecoOrigem(String enderecoOrigem){
        this.txtEnderecoOrigem.setText(enderecoOrigem);
    }
    
    public String getCidadeOrigem(){
        return txtCidadeOrigem.getText();
    }
    
    public void setCidadeOrigem(String cidadeOrigem){
        this.txtCidadeOrigem.setText(cidadeOrigem);
    }
     
    public String getEstadoOrigem(){
        return txtEstadoOrigem.getText();
    }
    
    public void setEstadoOrigem(String estadoOrigem){
        this.txtEstadoOrigem.setText(estadoOrigem);
    }
    
    public String getComplementoOrigem(){
        return txtComplementoOrigem.getText();
    }
    
    public void setComplementoOrigem(String complementoOrigem){
        this.txtComplementoOrigem.setText(complementoOrigem);
    }
    
    public String getHoraOrigem(){
        return this.txtHora.getText();
    }
    
    public void setHoraOrigem(String horaOrigem){
        this.txtHora.setText(horaOrigem);
    }
    
     public String getEnderecoDestino(){
        return txtEnderecoDestino.getText();
    }
    
    public void setEnderecoDestino(String enderecoDestino){
        this.txtEnderecoDestino.setText(enderecoDestino);
    }
    
    public String getCidadeDestino(){
        return txtCidadeDestino.getText();
    }
    
    public void setCidadeDestino(String cidadeDestino){
        this.txtCidadeDestino.setText(cidadeDestino);
    }
     
    public String getEstadoDestino(){
        return txtEstadoDestino.getText();
    }
    
    public void setEstadoDestino(String estadoDestino){
        this.txtEstadoDestino.setText(estadoDestino);
    }
    
    public String getComplementoDestino(){
        return txtComplementoDestino.getText();
    }
    
    public void setComplementoDestino(String complementoDestino){
        this.txtComplementoDestino.setText(complementoDestino);
    }
    
    public String getMedico(){
        return txtMedico.getText();
    }
    
    public void setMedico(String medico){
        this.txtMedico.setText(medico);
    }
    
    public String getEnfermeiro(){
        return txtEnfermeiro.getText();
    }
    
    public void setEnfermeiro(String enfermeiro){
        this.txtEnfermeiro.setText(enfermeiro);
    }
    
    public String getMotorista(){
        return txtMotorista.getText();
    }
    
    public void setMotorista(String motorista){
        this.txtMotorista.setText(motorista);
    }
    
    public String getOperador(){
        return txtOperador.getText();
    }
    
    public void setOperador(String operador){
        this.txtOperador.setText(operador);
    }
    
    public String getAmbulancia() {
        setAmbulancia();
        return ambulancia;
    }

    public void setAmbulancia() {
        if (checkBoxBasica.isSelected()) {
            ambulancia = "Basica";
        } else if (checkBoxSimples.isSelected()) {
            ambulancia = "Simples";
        } else if (checkBoxUTI.isSelected()) {
            ambulancia = "UTI";
        } else {
            ambulancia = "";
        }
    }

    public void setAmbulancia(String campo) {
        ambulancia = campo;
        if (ambulancia.equals("Basica")) {
            checkBoxBasica.setSelected(true);
        } else if (ambulancia.equals("Simples")) {
            checkBoxSimples.setSelected(true);
        } else {
            checkBoxUTI.setSelected(true);
        }
    }
    
    public String getObservacao(){
        return this.txtAreaObs.getText();
    }
    
    public void setObservacao(String obs){
        this.txtAreaObs.setText(obs);
    }
    
    public String getResponsavel(){
        return this.txtResponsavel.getText();
    }
    
    public void setResponsavel(String responsavel){
        this.txtResponsavel.setText(responsavel);
    }
    
    public String getUnidMedico(){
        return this.txtUnidMedico.getText();
    }
    
    public void setUnidMedico(String medico){
        this.txtUnidMedico.setText(medico);
    }
    
    public void btnGravarVisible(boolean mode){
        btnGravar.setVisible(mode);
    }
    
    public void btnVisualizarImpressaoVisible(boolean mode){
        btnImpressao.setVisible(mode);
    }
    
    public void btnEditarVisible(boolean mode){
        btnEditar.setVisible(mode);
    }
    
    public void btnHistoricoVisible(boolean mode){
        btnHistorico.setVisible(mode);
    }
    
    public void statusAllTxtField(boolean habilitar){
        txtNome.setEditable(habilitar);
        txtIdade.setEditable(habilitar);
        dateChooserSolicitacao.setEnabled(habilitar);
        dateChooserRemocao.setEnabled(habilitar);
        txtAreaDiagnostico.setEditable(habilitar);
        txtEnderecoOrigem.setEditable(habilitar);
        txtCidadeOrigem.setEditable(habilitar);
        txtEstadoOrigem.setEditable(habilitar);
        txtComplementoOrigem.setEditable(habilitar);
        txtHora.setEditable(habilitar);
        txtEnderecoDestino.setEditable(habilitar);
        txtCidadeDestino.setEditable(habilitar);
        txtEstadoDestino.setEditable(habilitar);
        txtComplementoDestino.setEditable(habilitar);
        txtMedico.setEditable(habilitar);
        txtEnfermeiro.setEditable(habilitar);
        txtMotorista.setEditable(habilitar);
        txtOperador.setEditable(habilitar);
        txtAreaObs.setEditable(habilitar);
        txtResponsavel.setEditable(habilitar);
        txtUnidMedico.setEditable(habilitar);  
    }
    
}
