package br.com.remocamp.view;

import br.com.remocamp.controller.PlantaoController;
import br.com.remocamp.model.Plantao;
import javax.swing.JOptionPane;


public class FormularioPlantao extends javax.swing.JInternalFrame {

    private java.sql.Date inicio;
    private java.sql.Date fim;
    private String ambulancia;
    private int idPlantao;
    private com.toedter.calendar.JDateChooser dateInicio;
    private com.toedter.calendar.JDateChooser dateFim;
    
    public FormularioPlantao() {
        initComponents();
        btnEditar.setVisible(false);
        btnImpressao.setVisible(false);
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEquipe = new javax.swing.JPanel();
        lbMedico = new javax.swing.JLabel();
        lbEnfermeiro = new javax.swing.JLabel();
        lbMotorista = new javax.swing.JLabel();
        lbOperador = new javax.swing.JLabel();
        txtMedico = new javax.swing.JTextField();
        txtEnfermeiro = new javax.swing.JTextField();
        txtMotorista = new javax.swing.JTextField();
        txtOperador = new javax.swing.JTextField();
        panelAmbulancia = new javax.swing.JPanel();
        checkBoxUTI = new javax.swing.JCheckBox();
        checkBoxBasica = new javax.swing.JCheckBox();
        checkBoxSimples = new javax.swing.JCheckBox();
        panelObs = new javax.swing.JPanel();
        jScrollPaneObs = new javax.swing.JScrollPane();
        txtAreaObs = new javax.swing.JTextArea();
        panelDestino = new javax.swing.JPanel();
        lbComplemento = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        lbCidade = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        panelEvento = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        txtNomeEvento = new javax.swing.JTextField();
        lbResponsavel = new javax.swing.JLabel();
        txtResponsavel = new javax.swing.JTextField();
        panelDateInicio = new javax.swing.JPanel();
        dateChooserInicio = new com.toedter.calendar.JDateChooser();
        panelDateFinal = new javax.swing.JPanel();
        dateChooserFim = new com.toedter.calendar.JDateChooser();
        PanelControle = new javax.swing.JPanel();
        btnImpressao = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Formulário plantão");

        panelEquipe.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipe"));

        lbMedico.setText("*Médico :");

        lbEnfermeiro.setText("*Enfermeiro(a) :");

        lbMotorista.setText("*Condutor:");

        lbOperador.setText("*Operador(a) :");

        txtMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicoActionPerformed(evt);
            }
        });

        txtEnfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnfermeiroActionPerformed(evt);
            }
        });

        txtMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotoristaActionPerformed(evt);
            }
        });

        txtOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOperadorActionPerformed(evt);
            }
        });

        panelAmbulancia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "*Ambulancia"));

        checkBoxUTI.setText("UTI");
        checkBoxUTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxUTIActionPerformed(evt);
            }
        });

        checkBoxBasica.setText("Básica");
        checkBoxBasica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxBasicaActionPerformed(evt);
            }
        });

        checkBoxSimples.setText("Simples");
        checkBoxSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSimplesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAmbulanciaLayout = new javax.swing.GroupLayout(panelAmbulancia);
        panelAmbulancia.setLayout(panelAmbulanciaLayout);
        panelAmbulanciaLayout.setHorizontalGroup(
            panelAmbulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAmbulanciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAmbulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxUTI)
                    .addComponent(checkBoxBasica)
                    .addComponent(checkBoxSimples))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelAmbulanciaLayout.setVerticalGroup(
            panelAmbulanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAmbulanciaLayout.createSequentialGroup()
                .addComponent(checkBoxUTI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxBasica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxSimples)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelEquipeLayout = new javax.swing.GroupLayout(panelEquipe);
        panelEquipe.setLayout(panelEquipeLayout);
        panelEquipeLayout.setHorizontalGroup(
            panelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbOperador)
                    .addComponent(lbMotorista)
                    .addComponent(lbEnfermeiro)
                    .addComponent(lbMedico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(panelAmbulancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        panelEquipeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEnfermeiro, txtMedico, txtMotorista, txtOperador});

        panelEquipeLayout.setVerticalGroup(
            panelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquipeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEquipeLayout.createSequentialGroup()
                        .addGroup(panelEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEquipeLayout.createSequentialGroup()
                                .addComponent(lbMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbEnfermeiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbMotorista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbOperador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelEquipeLayout.createSequentialGroup()
                                .addComponent(txtMedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEnfermeiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMotorista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOperador)))
                        .addGap(18, 18, 18))
                    .addGroup(panelEquipeLayout.createSequentialGroup()
                        .addComponent(panelAmbulancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        panelObs.setBorder(javax.swing.BorderFactory.createTitledBorder("Obs"));

        txtAreaObs.setColumns(20);
        txtAreaObs.setRows(5);
        jScrollPaneObs.setViewportView(txtAreaObs);

        javax.swing.GroupLayout panelObsLayout = new javax.swing.GroupLayout(panelObs);
        panelObs.setLayout(panelObsLayout);
        panelObsLayout.setHorizontalGroup(
            panelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneObs, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelObsLayout.setVerticalGroup(
            panelObsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObsLayout.createSequentialGroup()
                .addComponent(jScrollPaneObs, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelDestino.setBorder(javax.swing.BorderFactory.createTitledBorder("Destino"));

        lbComplemento.setText("Complemento :");

        lbEndereco.setText("*Endereço :");

        lbEstado.setText("*Estado :");

        lbCidade.setText("*Cidade :");

        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDestinoLayout = new javax.swing.GroupLayout(panelDestino);
        panelDestino.setLayout(panelDestinoLayout);
        panelDestinoLayout.setHorizontalGroup(
            panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEndereco)
                    .addComponent(lbCidade)
                    .addComponent(lbComplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEndereco)
                    .addGroup(panelDestinoLayout.createSequentialGroup()
                        .addGroup(panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtComplemento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(txtCidade, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(32, 32, 32)
                        .addComponent(lbEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 150, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDestinoLayout.setVerticalGroup(
            panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstado)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComplemento)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelEvento.setBorder(javax.swing.BorderFactory.createTitledBorder("Evento"));

        lbNome.setText("*Nome :");

        lbResponsavel.setText("*Responsável :");

        panelDateInicio.setBorder(javax.swing.BorderFactory.createTitledBorder("*Início"));

        javax.swing.GroupLayout panelDateInicioLayout = new javax.swing.GroupLayout(panelDateInicio);
        panelDateInicio.setLayout(panelDateInicioLayout);
        panelDateInicioLayout.setHorizontalGroup(
            panelDateInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDateInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateChooserInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDateInicioLayout.setVerticalGroup(
            panelDateInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDateInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateChooserInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelDateFinal.setBorder(javax.swing.BorderFactory.createTitledBorder("*Final"));

        javax.swing.GroupLayout panelDateFinalLayout = new javax.swing.GroupLayout(panelDateFinal);
        panelDateFinal.setLayout(panelDateFinalLayout);
        panelDateFinalLayout.setHorizontalGroup(
            panelDateFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDateFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateChooserFim, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDateFinalLayout.setVerticalGroup(
            panelDateFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDateFinalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateChooserFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelEventoLayout = new javax.swing.GroupLayout(panelEvento);
        panelEvento.setLayout(panelEventoLayout);
        panelEventoLayout.setHorizontalGroup(
            panelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEventoLayout.createSequentialGroup()
                .addGroup(panelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEventoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbNome)
                        .addGap(22, 22, 22)
                        .addComponent(txtNomeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelEventoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lbResponsavel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEventoLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(panelDateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(panelDateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        panelEventoLayout.setVerticalGroup(
            panelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEventoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(panelDateInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDateFinal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbResponsavel)
                    .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );

        btnImpressao.setText("Vizualizar impressão");
        btnImpressao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpressaoActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelControleLayout = new javax.swing.GroupLayout(PanelControle);
        PanelControle.setLayout(PanelControleLayout);
        PanelControleLayout.setHorizontalGroup(
            PanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImpressao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGravar)
                .addContainerGap())
        );
        PanelControleLayout.setVerticalGroup(
            PanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImpressao)
                    .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar))
                .addContainerGap())
        );

        PanelControleLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEditar, btnGravar, btnImpressao});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelObs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelEquipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PanelControle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {panelDestino, panelEquipe, panelEvento, panelObs});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(panelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(437, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleName("Formulário Plantão");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicoActionPerformed

    private void txtEnfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnfermeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnfermeiroActionPerformed

    private void txtMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotoristaActionPerformed

    private void txtOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOperadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOperadorActionPerformed

    private void checkBoxUTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxUTIActionPerformed
        if (checkBoxBasica.isSelected() || checkBoxSimples.isSelected()) {
            checkBoxBasica.setSelected(false);
            checkBoxSimples.setSelected(false);
        }
    }//GEN-LAST:event_checkBoxUTIActionPerformed

    private void checkBoxBasicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxBasicaActionPerformed
        if (checkBoxSimples.isSelected() || checkBoxUTI.isSelected()) {
            checkBoxSimples.setSelected(false);
            checkBoxUTI.setSelected(false);
        }
    }//GEN-LAST:event_checkBoxBasicaActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed

    }//GEN-LAST:event_txtEstadoActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        if(validarFormulario()){
            PlantaoController controller = new PlantaoController(this);
            controller.gravarFormulario();
            btnImpressao.setVisible(true);
            btnGravar.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Os campos obrigatórios não foram preenchidos", "Validação de formulário", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnImpressaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpressaoActionPerformed
            PlantaoController clt = new PlantaoController(this);
            clt.gerarFormulario();
            
    }//GEN-LAST:event_btnImpressaoActionPerformed

    private void checkBoxSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSimplesActionPerformed
        if (checkBoxBasica.isSelected() || checkBoxUTI.isSelected()) {
            checkBoxBasica.setSelected(false);
            checkBoxUTI.setSelected(false);
    }//GEN-LAST:event_checkBoxSimplesActionPerformed
    }
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        statusAllTxtField(true);
        
        if(btnEditar.getText().equals("Gravar")){
            if(validarFormulario()){
                PlantaoController controller = new PlantaoController(this);
                FormularioPlantao plantaoFormulario=controller.updatePlantao();
                dispose();
                Principal.desktopPane.add(plantaoFormulario);
                plantaoFormulario.setVisible(true);
             //   btnEditarVisible(false);
            //    btnVisualizarImpressaoVisible(true);
                return;
            }else{
                JOptionPane.showMessageDialog(this, "Os campos obrigatórios não foram preenchidos", "Validação de formulário", JOptionPane.ERROR_MESSAGE);
                return;
            }
         }
        
        if(btnEditar.getText().equals("Editar")){
           btnEditar.setText("Gravar");
           btnVisualizarImpressaoVisible(false);
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed
        
    private boolean validarFormulario(){
        if(txtNomeEvento.getText().isEmpty()){
            return false;
        }else if(dateChooserInicio == null){
            return false;
        }else if(dateChooserFim == null){
            return false;
        }else if(txtResponsavel.getText().isEmpty()){
            return false;
        }else if(txtEndereco.getText().isEmpty()){
            return false;
        }else if(txtCidade.getText().isEmpty()){
            return false;
        }else if(txtEstado.getText().isEmpty()){
            return false;
        }else if(txtMedico.getText().isEmpty()){
            return false;
        }else if(txtEnfermeiro.getText().isEmpty()){
            return false;
        }else if(txtMotorista.getText().isEmpty()){
            return false;
        }else if(txtOperador.getText().isEmpty()){
            return false;
        }else return !getAmbulancia().equals("");
  }

   
    private void setAmbulanciaFormulario(Plantao plantao){
    
        String tipo = plantao.getAmbulancia();
        
        if (tipo.equals("UTI")) {
            checkBoxUTI.setSelected(true);
        } else if (tipo.equals("Basica")) {
            checkBoxBasica.setSelected(true);
        } else {
            checkBoxSimples.setSelected(true);
        }
    }
    
    public void statusAllTxtField(boolean habilitar){
        txtNomeEvento.setEditable(habilitar);
        dateChooserInicio.setEnabled(habilitar);
        dateChooserFim.setEnabled(habilitar);
        txtResponsavel.setEditable(habilitar);
        txtEndereco.setEditable(habilitar);
        txtCidade.setEditable(habilitar);
        txtEstado.setEditable(habilitar);
        txtComplemento.setEditable(habilitar);
        txtMedico.setEditable(habilitar);
        txtEnfermeiro.setEditable(habilitar);
        txtMotorista.setEditable(habilitar);
        txtOperador.setEditable(habilitar);
        txtAreaObs.setEditable(habilitar);
    }

    public int getIdPlantao(){
        return idPlantao;
    }
    
    public void setIdPlantao(int id){
        this.idPlantao=id;
    }
    public String getNomeEvento() {
        return txtNomeEvento.getText();
    }

    public void setNomeEvento(String campo) {
        this.txtNomeEvento.setText(campo);
    }

    public java.sql.Date getInicio() {
        return inicio;
    }

    public void setInicio(java.sql.Date inicio) {
        this.inicio = inicio;
    }
    
    public java.sql.Date getFim() {
        return fim;
    }

    public void setFim(java.sql.Date fim) {
        this.fim = fim;
    }
    
     public String getResponsavel() {
        return txtResponsavel.getText();
    }

    public void setResponsavel(String campo) {
        this.txtResponsavel.setText(campo);
    }
    
     public String getEndereco() {
        return txtEndereco.getText();
    }

    public void setEndereco(String campo) {
        this.txtEndereco.setText(campo);
    }
    
     public String getCidade() {
        return txtCidade.getText();
    }

    public void setCidade(String campo) {
        this.txtCidade.setText(campo);
    }
    
     public String getEstado() {
        return txtEstado.getText();
    }

    public void setEstado(String campo) {
        this.txtEstado.setText(campo);
    }
    
     public String getComplemento() {
        return txtComplemento.getText();
    }

    public void setComplemento(String campo) {
        this.txtComplemento.setText(campo);
    }
    
     public String getMedico() {
        return txtMedico.getText();
    }

    public void setMedico(String campo) {
        this.txtMedico.setText(campo);
    }
    
    public String getEnfermeiro() {
        return txtEnfermeiro.getText();
    }

    public void setEnfermeiro(String campo) {
        this.txtEnfermeiro.setText(campo);
    }
    
    public String getMotorista() {
        return txtMotorista.getText();
    }

    public void setMotorista(String campo) {
        this.txtMotorista.setText(campo);
    }
    
    public String getOperador() {
        return txtOperador.getText();
    }

    public void setOperador(String campo) {
        this.txtOperador.setText(campo);
    }
    
     public String getObservacao() {
        return txtAreaObs.getText();
    }

    public void setObservacao(String campo) {
        this.txtAreaObs.setText(campo);
    }
    
    public String getAmbulancia() {
        setAmbulancia();
        return ambulancia;
    }

    public void setAmbulancia() {
        if (checkBoxBasica.isSelected()) {
            ambulancia = "Basica";
        } else if (checkBoxSimples.isSelected()) {
            ambulancia = "Simples";
        } else if (checkBoxUTI.isSelected()) {
            ambulancia = "UTI";
        }else{
            ambulancia = "";
        }
    }
    public void setAmbulancia(String campo){
        ambulancia = campo;
        if(ambulancia.equals("Basica")){
            checkBoxBasica.setSelected(true);
        }else if(ambulancia.equals("Simples")){
            checkBoxSimples.setSelected(true);
        }else{
            checkBoxUTI.setSelected(true);
        }
    }

    public com.toedter.calendar.JDateChooser getDateChoserInicio() {
        setDateChoserInicio(dateChooserInicio);
        return dateInicio;
    }

    public void setDateChoserInicio(com.toedter.calendar.JDateChooser dateChoserInicio) {
       dateInicio = dateChoserInicio;
    }

    public com.toedter.calendar.JDateChooser getDateChoserFim() {
        setDateChoserFim(dateChooserFim);
        return dateFim;
    }

    public void setDateChoserFim(com.toedter.calendar.JDateChooser dateChoserFim) {
        dateFim=dateChoserFim;
    }
    
    public void btnGravarVisible(boolean mode){
        btnGravar.setVisible(mode);
    }
    
    public void btnVisualizarImpressaoVisible(boolean mode){
        btnImpressao.setVisible(mode);
    }
    
    public void btnEditarVisible(boolean mode){
        btnEditar.setVisible(mode);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelControle;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnImpressao;
    private javax.swing.JCheckBox checkBoxBasica;
    private javax.swing.JCheckBox checkBoxSimples;
    private javax.swing.JCheckBox checkBoxUTI;
    private com.toedter.calendar.JDateChooser dateChooserFim;
    private com.toedter.calendar.JDateChooser dateChooserInicio;
    private javax.swing.JScrollPane jScrollPaneObs;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbComplemento;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbEnfermeiro;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbMedico;
    private javax.swing.JLabel lbMotorista;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbOperador;
    private javax.swing.JLabel lbResponsavel;
    private javax.swing.JPanel panelAmbulancia;
    private javax.swing.JPanel panelDateFinal;
    private javax.swing.JPanel panelDateInicio;
    private javax.swing.JPanel panelDestino;
    private javax.swing.JPanel panelEquipe;
    private javax.swing.JPanel panelEvento;
    private javax.swing.JPanel panelObs;
    private javax.swing.JTextArea txtAreaObs;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEnfermeiro;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtMotorista;
    private javax.swing.JTextField txtNomeEvento;
    private javax.swing.JTextField txtOperador;
    private javax.swing.JTextField txtResponsavel;
    // End of variables declaration//GEN-END:variables
}
