/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.remocamp.view;
import br.com.remocamp.controller.NotaFiscalController;
import br.com.remocamp.xlm.NotaFiscalXML;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author fabiano
 */
public class Principal extends javax.swing.JFrame {
	private JPanel contentPane;

    /**
     * Creates new form Principal2
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneAtividades = new javax.swing.JScrollPane();
        treeAtividades = new javax.swing.JTree();
        lbLogo = new javax.swing.JLabel();
        scrollPaneDesktop = new javax.swing.JScrollPane();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuItemAtualizarBase = new javax.swing.JMenuItem();
        menuItemSair = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuItemVersao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("2016 © REMOCAMP - AMBULÂNCIAS");

        treeAtividades.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Atividades");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Orderm de serviço");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nova ordem");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Remoção");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Plantão");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Consultas");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ordem de serviço");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Remoção");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Plantão");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Clientes");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Base de dados");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Funcionários");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Funcionários");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeAtividades.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treeAtividades.setAutoscrolls(true);
        treeAtividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeAtividadesMouseClicked(evt);
            }
        });
        scrollPaneAtividades.setViewportView(treeAtividades);
        treeAtividades.getAccessibleContext().setAccessibleParent(this);

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/remocamp/figuras/LOGOMARCA.jpg"))); // NOI18N

        scrollPaneDesktop.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollPaneDesktop.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPaneDesktop.setAutoscrolls(true);
        scrollPaneDesktop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrollPaneDesktop.setMaximumSize(new java.awt.Dimension(32767, 42767));

        desktopPane.setBackground(new java.awt.Color(30, 136, 171));
        desktopPane.setName(""); // NOI18N
        desktopPane.setPreferredSize(new java.awt.Dimension(1024, 900));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        scrollPaneDesktop.setViewportView(desktopPane);

        menuArquivo.setText("Arquivo");

        menuItemAtualizarBase.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuItemAtualizarBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/remocamp/figuras/open_icon.png"))); // NOI18N
        menuItemAtualizarBase.setText("Atualizar base de dados");
        menuItemAtualizarBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAtualizarBaseActionPerformed(evt);
            }
        });
        menuArquivo.add(menuItemAtualizarBase);

        menuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/remocamp/figuras/exit.jpg"))); // NOI18N
        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuItemSair);

        menuBar.add(menuArquivo);

        menuAjuda.setText("Ajuda");

        menuItemVersao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/remocamp/figuras/info_blue.png"))); // NOI18N
        menuItemVersao.setText("Versao");
        menuItemVersao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVersaoActionPerformed(evt);
            }
        });
        menuAjuda.add(menuItemVersao);

        menuBar.add(menuAjuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneAtividades, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLogo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPaneAtividades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1276, 718));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void treeAtividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeAtividadesMouseClicked
    
        if(evt.getClickCount()==2){
         String menu = treeAtividades.getAnchorSelectionPath()+"";
         
         if(menu.equals("[Atividades, Orderm de serviço, Nova ordem, Remoção]")){
            FormularioRemocao remocao = new FormularioRemocao();
            desktopPane.add(remocao).setLocation(90,0);
            remocao.setVisible(true);
         }else if(menu.equals("[Atividades, Orderm de serviço, Nova ordem, Plantão]")){
            FormularioPlantao plantao  = new FormularioPlantao();
            desktopPane.add(plantao).setLocation(90,0);
            plantao.setVisible(true);
         }else if(menu.equals("[Atividades, Consultas, Ordem de serviço, Remoção]")){
            SearchRemocao searchRemocao = new SearchRemocao();
            desktopPane.add(searchRemocao).setLocation(90,0);
            searchRemocao.setVisible(true);
         }else if(menu.equals("[Atividades, Consultas, Ordem de serviço, Plantão]")){
            SearchPlantao searchPlantao = new SearchPlantao();
            desktopPane.add(searchPlantao).setLocation(90,0);
            searchPlantao.setVisible(true);
         }else if(menu.equals("[Atividades, Consultas, Clientes, Base de dados]")){
            SearchNotaFiscal searchNotaFiscal = new SearchNotaFiscal();
            desktopPane.add(searchNotaFiscal).setLocation(90,0);
            searchNotaFiscal.setVisible(true);
         }
        }
    }//GEN-LAST:event_treeAtividadesMouseClicked

    private void menuItemAtualizarBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAtualizarBaseActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            if (fileChooser.getSelectedFile().getName().contains("xml")) {
                File selectedFile = fileChooser.getSelectedFile();
                NotaFiscalXML nf = new NotaFiscalXML(selectedFile);
                nf.getAllNotas();
                NotaFiscalController controller = new NotaFiscalController(nf.getNota());
                controller.adicionaNotas();
                JOptionPane.showMessageDialog(this, "Notas fiscais cadastradas com sucesso.");
            }else{
                JOptionPane.showMessageDialog(this, "Arquivo inválido");
            }
        }
    }//GEN-LAST:event_menuItemAtualizarBaseActionPerformed

    private void menuItemVersaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVersaoActionPerformed
          Versao versao = new Versao();
          versao.setVisible(true);
          
    }//GEN-LAST:event_menuItemVersaoActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemAtualizarBase;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemVersao;
    private javax.swing.JScrollPane scrollPaneAtividades;
    private javax.swing.JScrollPane scrollPaneDesktop;
    private javax.swing.JTree treeAtividades;
    // End of variables declaration//GEN-END:variables
}
